apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chattest-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: wso2is-shared
  volumeMode: Filesystem